# Generated by Django 5.2.10 on 2026-02-20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_profile_picture"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="followers",
            new_name="following",
        ),
        migrations.AlterField(
            model_name="user",
            name="following",
            field=models.ManyToManyField(
                blank=True,
                related_name="followers",
                symmetrical=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
